// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC53uayou1TRCbodSk5a3qPhzW9u13J_sc',
//     appId: '1:488895541856:web:4e04d1534d8d04d2448905',
//     messagingSenderId: '488895541856',
//     projectId: 'crime-alerts-16',
//     authDomain: 'crime-alerts-16.firebaseapp.com',
//     storageBucket: 'crime-alerts-16.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD9zGlC_6RIRxwp1jFv8uIXt-Y2lERRB40',
//     appId: '1:488895541856:android:3d0c727ec70ec53a448905',
//     messagingSenderId: '488895541856',
//     projectId: 'crime-alerts-16',
//     storageBucket: 'crime-alerts-16.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB7fOllJaUdYb3McMv24MNZgmiv0FwGdyM',
//     appId: '1:488895541856:ios:d64518661ec8d431448905',
//     messagingSenderId: '488895541856',
//     projectId: 'crime-alerts-16',
//     storageBucket: 'crime-alerts-16.appspot.com',
//     iosClientId: '488895541856-ajjbbmnd8jslrc0spcmrp4qr2pkhl7bi.apps.googleusercontent.com',
//     iosBundleId: 'com.example.crimeTestApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB7fOllJaUdYb3McMv24MNZgmiv0FwGdyM',
//     appId: '1:488895541856:ios:e12ba1a83d8921cd448905',
//     messagingSenderId: '488895541856',
//     projectId: 'crime-alerts-16',
//     storageBucket: 'crime-alerts-16.appspot.com',
//     iosClientId: '488895541856-j2rbon6js28ldf4iv19a5c74ivos28jr.apps.googleusercontent.com',
//     iosBundleId: 'com.example.crimeTestApp.RunnerTests',
//   );
// }
